# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  servers=[
        {
          :hostname => "c1-cp1",
          :ip => "192.168.56.100",
          :ssh_port => '2200'
        },
        {
          :hostname => "node1",
          :ip => "192.168.56.101",
          :ssh_port => '2201'
        },
        {
          :hostname => "node2",
          :ip => "192.168.56.102",
          :ssh_port => '2202'
        }
      ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|

      node.vm.box = "ubuntu/bionic64"

      node.vm.box_check_update = false

      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.usable_port_range = 0..65535

      node.ssh.forward_agent = true


      node.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "2048"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: <<-SHELL
        echo ${i}
      SHELL
    end
  end
end